#pragma once

#define WEASEL_CODE_NAME "9IME"
#define WEASEL_REG_KEY L"Software\\Rime\\9IME"
#define RIME_REG_KEY L"Software\\Rime"

#define STRINGIZE(x) #x
#define VERSION_STR(x) STRINGIZE(x)
#define WEASEL_VERSION VERSION_STR(VERSION_MAJOR.VERSION_MINOR.VERSION_PATCH)
